using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using BalanceBoard.App.Controls;
using BalanceBoard.App.Views;
namespace BalanceBoard.App;
public partial class MainWindow
{
    private readonly CheckBox _enableVJoyCheck = new() { Visibility = Visibility.Collapsed };
    private ConnectionToolbar ConnectionToolbar => DashboardView.ConnectionToolbar;
    private Border ConnectionChip => ConnectionToolbar.ConnectionChip;
    private TextBlock ConnectionChipText => ConnectionToolbar.ConnectionChipText;
    private Border VJoyChip => ConnectionToolbar.VJoyChip;
    private TextBlock VJoyChipText => ConnectionToolbar.VJoyChipText;
    private TextBlock StatusText => ConnectionToolbar.StatusText;
    private Button ShowLogButton => ConnectionToolbar.ShowLogButton;
    private Button ConnectButton => ConnectionToolbar.ConnectButton;
    private Button CancelButton => ConnectionToolbar.CancelButton;
    private Button DisconnectButton => ConnectionToolbar.DisconnectButton;
    private Button ExitButton => ConnectionToolbar.ExitButton;
    private Border PhysicalTestPanel => DashboardView.PhysicalTestPanel;
    private TextBlock PhysicalTestScenarioText => DashboardView.PhysicalTestScenarioText;
    private TextBlock PhysicalTestArtifactsText => DashboardView.PhysicalTestArtifactsText;
    private TextBlock PhysicalTestStepTitleText => DashboardView.PhysicalTestStepTitleText;
    private TextBlock PhysicalTestStepInstructionsText => DashboardView.PhysicalTestStepInstructionsText;
    private TextBlock PhysicalTestExpectedSignalText => DashboardView.PhysicalTestExpectedSignalText;
    private TextBlock PhysicalTestProgressText => DashboardView.PhysicalTestProgressText;
    private Button PhysicalTestPassButton => DashboardView.PhysicalTestPassButton;
    private Button PhysicalTestFailButton => DashboardView.PhysicalTestFailButton;
    private Button PhysicalTestSkipButton => DashboardView.PhysicalTestSkipButton;
    private Border BalancePanel => DashboardView.BalancePanel;
    private TextBlock DirectionText => DashboardView.DirectionText;
    private TextBlock ActiveActionsText => DashboardView.ActiveActionsText;
    private WrapPanel CalibrationButtonsPanel => DashboardView.CalibrationButtonsPanel;
    private Button TareButton => DashboardView.TareButton;
    private Button SetCenterButton => DashboardView.SetCenterButton;
    private Button ResetCenterButton => DashboardView.ResetCenterButton;
    private BalanceBoardVisual BoardVisual => DashboardView.BoardVisual;
    private TextBlock WeightText => DashboardView.WeightText;
    private TextBlock BalanceText => DashboardView.BalanceText;
    private TextBlock SensorText => DashboardView.SensorText;
    private TextBlock BoardButtonText => DashboardView.BoardButtonText;
    private TextBlock VJoyAxesText => DashboardView.VJoyAxesText;
    private Border DetailLevelCard => ProfilesView.DetailLevelCard;
    private ComboBox DetailLevelCombo => ProfilesView.DetailLevelCombo;
    private TextBlock DetailLevelDescription => ProfilesView.DetailLevelDescription;
    private Border ProfileCard => ProfilesView.ProfileCard;
    private ComboBox ProfileCombo => ProfilesView.ProfileCombo;
    private TextBlock ProfileHintText => ProfilesView.ProfileHintText;
    private UniformGrid ProfileButtonGrid => ProfilesView.ProfileButtonGrid;
    private Button GamePresetButton => ProfilesView.GamePresetButton;
    private Button MinecraftPresetButton => ProfilesView.MinecraftPresetButton;
    private Button DesktopPresetButton => ProfilesView.DesktopPresetButton;
    private Button PedalPresetButton => ProfilesView.PedalPresetButton;
    private Button MousePresetButton => ProfilesView.MousePresetButton;
    private Border CustomProfileCard => ProfilesView.CustomProfileCard;
    private ComboBox CustomProfileCombo => ProfilesView.CustomProfileCombo;
    private Button SaveProfileButton => ProfilesView.SaveProfileButton;
    private Button LoadProfileButton => ProfilesView.LoadProfileButton;
    private Button DeleteProfileButton => ProfilesView.DeleteProfileButton;
    private Button UpdateProfileButton => ProfilesView.UpdateProfileButton;
    private Button ExportProfileButton => ProfilesView.ExportProfileButton;
    private Button ImportProfileButton => ProfilesView.ImportProfileButton;
    private TextBlock CustomProfileStatusText => ProfilesView.CustomProfileStatusText;
    private Button ResetDefaultsButton => ProfilesView.ResetDefaultsButton;
    private Border ThemeCard => ProfilesView.ThemeCard;
    private StackPanel ThemeOptionsPanel => ProfilesView.ThemeOptionsPanel;
    private CheckBox AutoConnectCheck => ProfilesView.AutoConnectCheck;
    private CheckBox StartMinimizedCheck => ProfilesView.StartMinimizedCheck;
    private StackPanel ThemeRow => ProfilesView.ThemeRow;
    private ComboBox ThemeCombo => ProfilesView.ThemeCombo;
    private Border SensitivityCard => FineTuningView.SensitivityCard;
    private CheckBox SimpleSensitivityCheck => FineTuningView.SimpleSensitivityCheck;
    private WrapPanel SimpleSensitivityPanel => FineTuningView.SimpleSensitivityPanel;
    private Button SensitivityLowButton => FineTuningView.SensitivityLowButton;
    private Button SensitivityMediumButton => FineTuningView.SensitivityMediumButton;
    private Button SensitivityHighButton => FineTuningView.SensitivityHighButton;
    private Button SensitivityHighlyButton => FineTuningView.SensitivityHighlyButton;
    private Button SensitivityHairTriggerButton => FineTuningView.SensitivityHairTriggerButton;
    private StackPanel SimpleJumpPanel => FineTuningView.SimpleJumpPanel;
    private TextBlock SimpleJumpLabel => FineTuningView.SimpleJumpLabel;
    private WrapPanel SimpleJumpButtonsPanel => FineTuningView.SimpleJumpButtonsPanel;
    private Button JumpEasyButton => FineTuningView.JumpEasyButton;
    private Button JumpNormalButton => FineTuningView.JumpNormalButton;
    private Button JumpHardButton => FineTuningView.JumpHardButton;
    private Border FineTuneSection => FineTuningView.FineTuneSection;
    private TextBlock FineTuneHintText => FineTuningView.FineTuneHintText;
    private StackPanel StandardSensitivityPanel => FineTuningView.StandardSensitivityPanel;
    private CheckBox OneFootModeCheck => FineTuningView.OneFootModeCheck;
    private TextBlock DeadzoneLabel => FineTuningView.DeadzoneLabel;
    private Slider DeadzoneSlider => FineTuningView.DeadzoneSlider;
    private CheckBox SplitAxisDeadzoneCheck => FineTuningView.SplitAxisDeadzoneCheck;
    private StackPanel SplitAxisDeadzonePanel => FineTuningView.SplitAxisDeadzonePanel;
    private TextBlock DeadzoneLeftRightLabel => FineTuningView.DeadzoneLeftRightLabel;
    private Slider DeadzoneLeftRightSlider => FineTuningView.DeadzoneLeftRightSlider;
    private TextBlock DeadzoneForwardBackwardLabel => FineTuningView.DeadzoneForwardBackwardLabel;
    private Slider DeadzoneForwardBackwardSlider => FineTuningView.DeadzoneForwardBackwardSlider;
    private TextBlock SensitivityLabel => FineTuningView.SensitivityLabel;
    private Slider SensitivitySlider => FineTuningView.SensitivitySlider;
    private CheckBox LockLeftRightAxisCheck => FineTuningView.LockLeftRightAxisCheck;
    private CheckBox LockForwardBackwardAxisCheck => FineTuningView.LockForwardBackwardAxisCheck;
    private CheckBox SplitAxisSensitivityCheck => FineTuningView.SplitAxisSensitivityCheck;
    private StackPanel SplitAxisSensitivityPanel => FineTuningView.SplitAxisSensitivityPanel;
    private TextBlock SensitivityLeftRightLabel => FineTuningView.SensitivityLeftRightLabel;
    private Slider SensitivityLeftRightSlider => FineTuningView.SensitivityLeftRightSlider;
    private TextBlock SensitivityForwardBackwardLabel => FineTuningView.SensitivityForwardBackwardLabel;
    private Slider SensitivityForwardBackwardSlider => FineTuningView.SensitivityForwardBackwardSlider;
    private TextBlock JumpThresholdLabel => FineTuningView.JumpThresholdLabel;
    private Slider JumpThresholdSlider => FineTuningView.JumpThresholdSlider;
    private StackPanel InvertPanel => FineTuningView.InvertPanel;
    private CheckBox InvertXCheck => FineTuningView.InvertXCheck;
    private CheckBox InvertYCheck => FineTuningView.InvertYCheck;
    private StackPanel AdvancedSensitivityPanel => FineTuningView.AdvancedSensitivityPanel;
    private TextBlock TriggerLeftRightLabel => FineTuningView.TriggerLeftRightLabel;
    private Slider TriggerLeftRightSlider => FineTuningView.TriggerLeftRightSlider;
    private TextBlock TriggerForwardBackwardLabel => FineTuningView.TriggerForwardBackwardLabel;
    private Slider TriggerForwardBackwardSlider => FineTuningView.TriggerForwardBackwardSlider;
    private TextBlock JumpHoldLabel => FineTuningView.JumpHoldLabel;
    private Slider JumpHoldSlider => FineTuningView.JumpHoldSlider;
    private ComboBox ResponseCurveCombo => FineTuningView.ResponseCurveCombo;
    private Border KeyboardSection => AdvancedView.KeyboardSection;
    private ActionBindingRow BindLeft => AdvancedView.BindLeft;
    private ActionBindingRow BindRight => AdvancedView.BindRight;
    private ActionBindingRow BindForward => AdvancedView.BindForward;
    private ActionBindingRow BindBackward => AdvancedView.BindBackward;
    private ActionBindingRow BindJump => AdvancedView.BindJump;
    private ActionBindingRow BindModifier => AdvancedView.BindModifier;
    private ActionBindingRow BindDiagonalLeft => AdvancedView.BindDiagonalLeft;
    private ActionBindingRow BindDiagonalRight => AdvancedView.BindDiagonalRight;
    private ActionBindingRow BindBoardButton => AdvancedView.BindBoardButton;
    private Border VJoySection => AdvancedView.VJoySection;
    private ComboBox OutputModeCombo => AdvancedView.OutputModeCombo;
    private CheckBox EnableVJoyCheck => _enableVJoyCheck;
    private CheckBox DisableActionsCheck => AdvancedView.DisableActionsCheck;
    private CheckBox SendCgCheck => AdvancedView.SendCgCheck;
    private CheckBox SendSensorsCheck => AdvancedView.SendSensorsCheck;
    private CheckBox MapJumpVJoyCheck => AdvancedView.MapJumpVJoyCheck;
    private StackPanel JumpVJoyPanel => AdvancedView.JumpVJoyPanel;
    private ComboBox JumpVJoyButtonCombo => AdvancedView.JumpVJoyButtonCombo;
    private ComboBox VJoyDeviceCombo => AdvancedView.VJoyDeviceCombo;
    private TextBlock VJoyDeviceDetailsText => AdvancedView.VJoyDeviceDetailsText;
    private Button ConfigureVJoyButton => AdvancedView.ConfigureVJoyButton;
    private Button GetVJoyButton => AdvancedView.GetVJoyButton;
    private Border CalibrationSection => AdvancedView.CalibrationSection;
    private CheckBox AutoTareCheck => AdvancedView.AutoTareCheck;
    private Border PerformanceSection => AdvancedView.PerformanceSection;
    private TextBlock PollIntervalLabel => AdvancedView.PollIntervalLabel;
    private Slider PollIntervalSlider => AdvancedView.PollIntervalSlider;
    private Border DiagnosticsSection => AdvancedView.DiagnosticsSection;
    private TextBlock HealthSummaryText => AdvancedView.HealthSummaryText;
    private TextBlock VJoyStatusText => AdvancedView.VJoyStatusText;
    private Button RunHealthCheckButton => AdvancedView.RunHealthCheckButton;
    private Button CopyReportButton => AdvancedView.CopyReportButton;
    private Border LiveLogPanel => SessionLogPanel.LiveLogPanel;
    private Expander SessionLogExpander => SessionLogPanel.SessionLogExpander;
    private TextBlock LogPreviewText => SessionLogPanel.LogPreviewText;
    private Button ClearLogViewButton => SessionLogPanel.ClearLogViewButton;
    private Button OpenLogFolderButton => SessionLogPanel.OpenLogFolderButton;
    private TextBox LogBox => SessionLogPanel.LogBox;
    private void OnActionBindingChanged(object? sender, EventArgs e) => ActionBinding_Changed(sender!, e);

    private void WireViewEvents()
    {
        ShowLogButton.Click += ShowLogButton_Click;
        ConnectButton.Click += ConnectButton_Click;
        CancelButton.Click += CancelButton_Click;
        DisconnectButton.Click += DisconnectButton_Click;
        ExitButton.Click += ExitButton_Click;
        PhysicalTestPassButton.Click += PhysicalTestPassButton_Click;
        PhysicalTestFailButton.Click += PhysicalTestFailButton_Click;
        PhysicalTestSkipButton.Click += PhysicalTestSkipButton_Click;
        TareButton.Click += Tare_Click;
        SetCenterButton.Click += SetCenter_Click;
        ResetCenterButton.Click += ResetCenter_Click;
        DetailLevelCombo.SelectionChanged += DetailLevelCombo_SelectionChanged;
        ProfileCombo.SelectionChanged += ProfileCombo_SelectionChanged;
        GamePresetButton.Click += GamePreset_Click;
        MinecraftPresetButton.Click += MinecraftPreset_Click;
        DesktopPresetButton.Click += KeyboardPreset_Click;
        PedalPresetButton.Click += PedalPreset_Click;
        MousePresetButton.Click += MousePreset_Click;
        SaveProfileButton.Click += SaveProfileButton_Click;
        LoadProfileButton.Click += LoadProfileButton_Click;
        DeleteProfileButton.Click += DeleteProfileButton_Click;
        UpdateProfileButton.Click += UpdateProfileButton_Click;
        ExportProfileButton.Click += ExportProfileButton_Click;
        ImportProfileButton.Click += ImportProfileButton_Click;
        ResetDefaultsButton.Click += ResetDefaultsButton_Click;
        AutoConnectCheck.Checked += SettingChanged; AutoConnectCheck.Unchecked += SettingChanged;
        StartMinimizedCheck.Checked += SettingChanged; StartMinimizedCheck.Unchecked += SettingChanged;
        ThemeCombo.SelectionChanged += ThemeCombo_SelectionChanged;
        SimpleSensitivityCheck.Checked += SettingChanged; SimpleSensitivityCheck.Unchecked += SettingChanged;
        SensitivityLowButton.Click += SensitivityLow_Click;
        SensitivityMediumButton.Click += SensitivityMedium_Click;
        SensitivityHighButton.Click += SensitivityHigh_Click;
        SensitivityHighlyButton.Click += SensitivityHighly_Click;
        SensitivityHairTriggerButton.Click += SensitivityHairTrigger_Click;
        JumpEasyButton.Click += JumpEasy_Click; JumpNormalButton.Click += JumpNormal_Click; JumpHardButton.Click += JumpHard_Click;
        OneFootModeCheck.Checked += OneFootMode_Changed; OneFootModeCheck.Unchecked += OneFootMode_Changed;
        DeadzoneSlider.ValueChanged += SettingChanged;
        SplitAxisDeadzoneCheck.Checked += SplitAxisDeadzone_Changed; SplitAxisDeadzoneCheck.Unchecked += SplitAxisDeadzone_Changed;
        DeadzoneLeftRightSlider.ValueChanged += SettingChanged; DeadzoneForwardBackwardSlider.ValueChanged += SettingChanged;
        SensitivitySlider.ValueChanged += SettingChanged;
        LockLeftRightAxisCheck.Checked += AxisLock_Changed; LockLeftRightAxisCheck.Unchecked += AxisLock_Changed;
        LockForwardBackwardAxisCheck.Checked += AxisLock_Changed; LockForwardBackwardAxisCheck.Unchecked += AxisLock_Changed;
        SplitAxisSensitivityCheck.Checked += SplitAxisSensitivity_Changed; SplitAxisSensitivityCheck.Unchecked += SplitAxisSensitivity_Changed;
        SensitivityLeftRightSlider.ValueChanged += SettingChanged; SensitivityForwardBackwardSlider.ValueChanged += SettingChanged;
        JumpThresholdSlider.ValueChanged += SettingChanged;
        InvertXCheck.Checked += SettingChanged; InvertXCheck.Unchecked += SettingChanged;
        InvertYCheck.Checked += SettingChanged; InvertYCheck.Unchecked += SettingChanged;
        TriggerLeftRightSlider.ValueChanged += SettingChanged; TriggerForwardBackwardSlider.ValueChanged += SettingChanged;
        JumpHoldSlider.ValueChanged += SettingChanged;
        ResponseCurveCombo.SelectionChanged += ResponseCurveCombo_SelectionChanged;
        BindLeft.BindingChanged += OnActionBindingChanged; BindRight.BindingChanged += OnActionBindingChanged;
        BindForward.BindingChanged += OnActionBindingChanged; BindBackward.BindingChanged += OnActionBindingChanged;
        BindJump.BindingChanged += OnActionBindingChanged; BindModifier.BindingChanged += OnActionBindingChanged;
        BindDiagonalLeft.BindingChanged += OnActionBindingChanged; BindDiagonalRight.BindingChanged += OnActionBindingChanged;
        BindBoardButton.BindingChanged += OnActionBindingChanged;
        OutputModeCombo.SelectionChanged += OutputModeCombo_SelectionChanged;
        SendCgCheck.Checked += SettingChanged; SendCgCheck.Unchecked += SettingChanged;
        SendSensorsCheck.Checked += SettingChanged; SendSensorsCheck.Unchecked += SettingChanged;
        MapJumpVJoyCheck.Checked += SettingChanged; MapJumpVJoyCheck.Unchecked += SettingChanged;
        JumpVJoyButtonCombo.SelectionChanged += SettingChanged;
        VJoyDeviceCombo.SelectionChanged += VJoyDeviceCombo_SelectionChanged;
        ConfigureVJoyButton.Click += ConfigureVJoyButton_Click; GetVJoyButton.Click += GetVJoyButton_Click;
        AutoTareCheck.Checked += SettingChanged; AutoTareCheck.Unchecked += SettingChanged;
        PollIntervalSlider.ValueChanged += SettingChanged;
        RunHealthCheckButton.Click += RunHealthCheckButton_Click;
        CopyReportButton.Click += CopyReportButton_Click;
        AdvancedView.OpenLogFolderFromDiagnosticsButton.Click += OpenLogFolderButton_Click;
        SessionLogExpander.Expanded += SessionLogExpander_Changed; SessionLogExpander.Collapsed += SessionLogExpander_Changed;
        ClearLogViewButton.Click += ClearLogViewButton_Click; OpenLogFolderButton.Click += OpenLogFolderButton_Click;
    }
}
